
PROJECT=jdksmidi
PROJECT_NAME=libjdksmidi
PROJECT_VERSION=2.2
PROJECT_EMAIL=<jeffk@jdkoftinoff.com>
PROJECT_LICENSE=GPL
PROJECT_MAINTAINER=Jeff Koftinoff <jeffk@jdkoftinoff.com>
PROJECT_COPYRIGHT=1988-2010 by J.D. Koftinoff Software, Ltd. and others, please see CONTRIBUTORS file.
PROJECT_COMPANY=J.D. Koftinoff Software, ltd.
PROJECT_DESCRIPTION=C++ MIDI Library.
PROJECT_README_FILE=$(PROJECT_TOP_DIR)/README.txt
PROJECT_DEV_README_FILE=$(PROJECT_TOP_DIR)/README.txt
PROJECT_DOCS_DEV_README_FILE=$(PROJECT_TOP_DIR)/README.txt
PROJECT_LICENSE_FILE=$(PROJECT_TOP_DIR)/COPYING

TARGET_DIR_STYLE?=simple

TOP_LIB_DIRS+=.

DEFINES_MINGW32+=
LDLIBS_MINGW32+=-lwinmm
COMPILE_FLAGS_MINGW32+=-mthreads

DEFINES_CYGWIN+=
LDLIBS_CYGWIN+=
COMPILE_FLAGS_CYGWIN+=

DEFINES_LINUX+=
LDLIBS_LINUX+=
COMPILE_FLAGS_LINUX+=

DEFINES_MACOSX+=
LDLIBS_MACOSX+=
COMPILE_FLAGS_MACOSX+=

DEFINES_MACOSX_PPC+=
LDLIBS_MACOSX_PPC+=
COMPILE_FLAGS_MACOSX_PPC+=

DEFINES_MACOSX_I386+=
LDLIBS_MACOSX_I386+=
COMPILE_FLAGS_MACOSX_I386+=

DEFINES_MACOSX_UNIVERSAL+=
LDLIBS_MACOSX_UNIVERSAL+=
COMPILE_FLAGS_MACOSX_UNIVERSAL+=
